# version:     "0026--06-Sep-2022"
copyright:   "2022"
author:      "valenciusap17"
name:        "Valencius Apriady Primayudha"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/valenciusap17/"
myloglink:   "/TXT/mylog.txt"
tarballlink: "https://os.vlsm.org/Log/valenciusap17.tar.bz2.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
